### ISSUE TITLE
书本案例代码

### ISSUE THREAD

**Issue by WwYyFan** [LiveStockShapeAnalysis/Point-Cloud-Processing-example#1]
@LiveStockShapeAnalysis 
你好，我购买了《点云库pcl从入门到精通》这本书，但是书上很多实例解析的代码都不全，这个仓库也没有提供相关的代码，请问可否提供这部分的代码来更好的学习？

**Comment by ilcamf** [comment]
你好，我购买了《点云库pcl从入门到精通》这本书，为何从第十四章到第二十章案例代码不提供，这个就不厚道了，我就是冲着案例代码才买的。。。。哭哭哭

**Comment by LiveStockShapeAnalysis** [comment]
没有公开源码的案例，都是合作项目或一些公司的产品相关，都共享出来基本不现实。书中也交代了。
